# Generated by Django 6.0.1 on 2026-01-12 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HojaDeVida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('perfil', models.TextField()),
                ('educacion', models.TextField()),
                ('experiencia', models.TextField()),
                ('habilidades', models.TextField()),
            ],
        ),
    ]
