# Generated by Django 6.0.1 on 2026-01-20 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_hojadevida_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('imagen', models.ImageField(upload_to='certificados/')),
                ('fecha', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
