# Generated by Django 6.0.1 on 2026-01-20 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_certificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificado',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='certificados/pdf/'),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='certificados/'),
        ),
    ]
